<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.0.0.379
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Отправка Форма Arteks | Transport',
	'heading' => 'Отправка новой формы',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Отмечено',
		'checkbox_unchecked' => 'Флажок не установлен',
		'submitted_from' => 'Формы, отправленные с веб-сайта: %s',
		'submitted_by' => 'IP-адрес посетителя: %s',
		'too_many_submissions' => 'Недопустимо высокое количество отправок с этого IP-адреса за последнее время',
		'failed_to_send_email' => 'Не удалось отправить сообщение эл. почты',
		'invalid_reCAPTCHA_private_key' => 'Недействительный закрытый ключ reCAPTCHA.',
		'invalid_reCAPTCHA2_private_key' => 'Недействительный закрытый ключ reCAPTCHA 2.0.',
		'invalid_reCAPTCHA2_server_response' => 'Недействительный ответ сервера reCAPTCHA 2.0.',
		'invalid_field_type' => 'Неизвестный тип поля \'%s\'.',
		'invalid_form_config' => 'Недопустимая конфигурация поля \"%s\".',
		'unknown_method' => 'Неизвестный метод запроса сервера'
	),
	'email' => array(
		'from' => 'arteks@arteks.ee',
		'to' => 'arteks@arteks.ee'
	),
	'fields' => array(
		'custom_U1611' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Заказчик',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Заказчик\' не может быть пустым.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'E-mail',
			'required' => false,
			'errors' => array(
				'format' => 'Поле \'E-mail\' содержит недействительное сообщение эл. почты.'
			)
		),
		'custom_U1587' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Контактная персона',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Контактная персона\' не может быть пустым.'
			)
		),
		'custom_U1583' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Номер телефона',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Номер телефона\' не может быть пустым.'
			)
		),
		'custom_U1591' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Отправитель груза',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Отправитель груза\' не может быть пустым.'
			)
		),
		'custom_U1579' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Адрес загрузки',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Адрес загрузки\' не может быть пустым.'
			)
		),
		'custom_U1603' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Контактная персона на загрузке',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Контактная персона на загрузке\' не может быть пустым.'
			)
		),
		'custom_U1595' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Телефон контактной персоны',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Телефон контактной персоны\' не может быть пустым.'
			)
		),
		'custom_U1607' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Получатель груза',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Получатель груза\' не может быть пустым.'
			)
		),
		'custom_U1711' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'Адрес получателя',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Адрес получателя\' не может быть пустым.'
			)
		),
		'custom_U1723' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'Контактная персона получателя',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Контактная персона получателя\' не может быть пустым.'
			)
		),
		'custom_U1735' => array(
			'order' => 12,
			'type' => 'string',
			'label' => 'Контактный телефон получателя',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Контактный телефон получателя\' не может быть пустым.'
			)
		),
		'custom_U1759' => array(
			'order' => 13,
			'type' => 'string',
			'label' => 'Количество груза',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Количество груза\' не может быть пустым.'
			)
		),
		'custom_U1771' => array(
			'order' => 14,
			'type' => 'string',
			'label' => 'Цена перевозки',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Цена перевозки\' не может быть пустым.'
			)
		),
		'custom_U1915' => array(
			'order' => 15,
			'type' => 'string',
			'label' => 'Сообщение',
			'required' => true,
			'errors' => array(
				'required' => 'Поле \'Сообщение\' не может быть пустым.'
			)
		)
	)
);

process_form($form);
?>
